### PR TITLE
fix: add security startup warnings for production environments

### LINKED ISSUE #70: BUG: No validation prevents trust.development_mode in production
## Summary

The server starts without warning or error when `trust.development_mode: true` is configured in a production environment. This development mode bypasses trust evaluation entirely, which is a serious security risk if accidentally deployed to production.

## Current Behavior

When `trust.development_mode: true` is set in the configuration, the server accepts all trust evaluations unconditionally without any warning, regardless of the deployment environment.

## Expected Behavior

The server should:
1. Refuse to start if `trust.development_mode: true` AND `ENVIRONMENT=production` (or similar production indicator)
2. At minimum, log a prominent WARNING at startup if development mode is enabled

## Security Impact

- **Risk R3**: Misconfigured trust evaluation leads to unauthorized access
- **Vulnerability S4**: No runtime validation of security-critical configuration

## Proposed Fix

Add startup validation in `internal/server/server.go`:

```go
if cfg.Trust.DevelopmentMode && os.Getenv("ENVIRONMENT") == "production" {
    return fmt.Errorf("trust.development_mode cannot be enabled in production environment")
}
```

Or at minimum:

```go
if cfg.Trust.DevelopmentMode {
    slog.Warn("SECURITY WARNING: trust.development_mode is enabled - all trust evaluations will pass")
}
```

## RSA Reference

This issue addresses **K2** from the SIROS ID Risk- och sårbarhetsanalys (RSA).

### LINKED ISSUE #71: BUG: No warning when CORS wildcard (*) is used in production
## Summary

The server starts without warning when `cors.allowed_origins` contains `*` (wildcard) in a production environment. This permissive CORS configuration allows any origin to make authenticated requests, which is a security risk.

## Current Behavior

When `cors.allowed_origins: ["*"]` is configured, the server accepts cross-origin requests from any domain without any warning, regardless of the deployment environment.

## Expected Behavior

The server should log a prominent WARNING at startup if:
- `cors.allowed_origins` contains `*` AND
- `ENVIRONMENT=production` (or similar production indicator)

## Security Impact

- **Risk R8**: Overly permissive CORS allows malicious sites to make authenticated API calls
- **Vulnerability S11**: No validation of security-critical CORS configuration

## Proposed Fix

Add startup validation in `internal/server/server.go`:

```go
for _, origin := range cfg.CORS.AllowedOrigins {
    if origin == "*" && os.Getenv("ENVIRONMENT") == "production" {
        slog.Warn("SECURITY WARNING: CORS wildcard (*) is configured in production - this allows any origin to make authenticated requests")
        break
    }
}
```

## RSA Reference

This issue addresses **K3** from the SIROS ID Risk- och sårbarhetsanalys (RSA).

### PR DESCRIPTION
**Pull request by leifj**
## Summary

Adds security configuration validation at startup that logs warnings about potentially dangerous configurations.

### Issue #70: Trust Evaluation Warning
When trust evaluation is disabled (no PDP URL configured), the server now logs a warning:
```
SECURITY: Trust evaluation is disabled - all issuers/verifiers will be accepted without verification
```

In production environments (detected via `ENVIRONMENT=production`, `GO_ENV=production`, or `APP_ENV=production`):
```
SECURITY WARNING: Trust evaluation is disabled in production environment
```

### Issue #71: CORS Wildcard Warning
When CORS allowed_origins contains `*`, the server logs a warning:
```
SECURITY: CORS wildcard (*) configured - allows requests from any origin
```

In production environments:
```
SECURITY WARNING: CORS wildcard (*) is configured in production - this allows any origin to make authenticated requests
```

## Testing
- Build passes
- No production code paths affected (logging only)

## Related
- Closes #70
- Closes #71
- RSA (Risk- och sårbarhetsanalys) items K2 and K3

### CODE REVIEW

File: cmd/server/main.go [hunk 1]
```diff
@@ -87,6 +87,49 @@ func main() {
...
+		os.Getenv("GO_ENV") == "production" ||
+		os.Getenv("APP_ENV") == "production"
+
+	if backendCfg != nil {
+		// Issue #70: Warn when trust evaluation is disabled (allows any issuer/verifier)
+		if !backendCfg.Trust.IsIssuerTrustEnabled() || !backendCfg.Trust.IsVerifierTrustEnabled() {
+			level := zap.WarnLevel
+			msg := "SECURITY: Trust evaluation is disabled - all issuers/verifiers will be accepted without verification"
+
+			if isProduction {
```
[the remark this answers is not in the document]
Comment (leifj) [reply cmd/server/main.go]: Fixed in 4ad0fbd. Cached both results into `issuerEnabled`/`verifierEnabled` locals and reuse them throughout.

File: cmd/server/main.go [hunk 2]
```diff
@@ -87,6 +87,49 @@ func main() {
...
+
+			if !backendCfg.Trust.IsIssuerTrustEnabled() && !backendCfg.Trust.IsVerifierTrustEnabled() {
+				logger.Log(level, msg,
+					zap.Bool("issuer_trust_enabled", false),
+					zap.Bool("verifier_trust_enabled", false))
+			} else if !backendCfg.Trust.IsIssuerTrustEnabled() {
+				logger.Log(level, msg+" for issuers",
+					zap.Bool("issuer_trust_enabled", false))
+			} else {
+				logger.Log(level, msg+" for verifiers",
```
[the remark this answers is not in the document]
Comment (leifj) [reply cmd/server/main.go]: Fixed in 4ad0fbd. Each case now has its own distinct message: both disabled uses "issuers and verifiers", issuer-only says "Issuer trust evaluation is disabled - all issuers will be accepted", verifier-only says the same for verifiers. No more misleading appended suffixes.

File: cmd/server/main.go [hunk 3]
```diff
@@ -87,6 +87,49 @@ func main() {
...
+
+		// Issue #71: Warn when CORS allows wildcard origin
+		for _, origin := range backendCfg.Server.CORS.AllowedOrigins {
+			if origin == "*" {
+				msg := "SECURITY: CORS wildcard (*) configured - allows requests from any origin"
+				if isProduction {
+					msg = "SECURITY WARNING: CORS wildcard (*) is configured in production - this allows any origin to make authenticated requests"
+				}
+				logger.Warn(msg,
+					zap.Strings("allowed_origins", backendCfg.Server.CORS.AllowedOrigins))
```
[the remark this answers is not in the document]
Comment (leifj) [reply cmd/server/main.go]: Already addressed in the initial commit (873c1b8) - the CORS warning already logs `allow_credentials`, `allowed_headers`, and `allowed_methods` alongside `allowed_origins`.

File: cmd/server/main.go [hunk 4]
```diff
@@ -87,6 +87,63 @@ func main() {
...
+					zap.Bool("verifier_trust_enabled", false))
+			}
+		}
+
+		// Issue #71: Warn when CORS allows wildcard origin
+		for _, origin := range backendCfg.Server.CORS.AllowedOrigins {
+			if origin == "*" {
+				msg := "SECURITY: CORS wildcard (*) configured - allows requests from any origin"
+				if isProduction {
+					msg = "SECURITY WARNING: CORS wildcard (*) is configured in production - this allows any origin to make authenticated requests"
```
Comment (s-jairl) [inline cmd/server/main.go]: This phrasing is not correct - it would be if we relied on cookie based authentication, but we use custom headers. A better version would be "this allows any origin to make requests"

File: cmd/server/main.go [hunk 5]
```diff
@@ -87,6 +87,63 @@ func main() {
...
+		// Issue #70: Warn when trust evaluation is disabled (allows any issuer/verifier)
+		// Cache the results to avoid repeated calls
+		issuerEnabled := backendCfg.Trust.IsIssuerTrustEnabled()
+		verifierEnabled := backendCfg.Trust.IsVerifierTrustEnabled()
+
+		if !issuerEnabled || !verifierEnabled {
+			level := zap.WarnLevel
+
+			if !issuerEnabled && !verifierEnabled {
+				msg := "SECURITY: Trust evaluation is disabled - all issuers and verifiers will be accepted without verification"
```
Comment (s-jairl) [inline cmd/server/main.go]: Is there a cleaner way to handle this besides duplicating the messages but with added "WARNING" prefix? Should the log messages really be different between debug and prod?

**Review by s-jairl — CHANGES_REQUESTED** [review]

File: cmd/server/main.go (hunk 4 above)
Comment (leifj) [reply cmd/server/main.go]: Fixed in 4d4550c. Changed to 'allows any origin to make requests' — you're right, we use custom Authorization headers, not cookie-based auth.

File: cmd/server/main.go (hunk 5 above)
Comment (leifj) [reply cmd/server/main.go]: Fixed in 4d4550c. Removed the duplicate message pattern entirely. Now uses a single message string per case and differentiates by log level: `Error` in production, `Warn` otherwise. Added `production=true/false` structured field so alerting pipelines can filter.

**Review by s-jairl — APPROVED** [review]
